import {
  Endorsement,
  PhotographyAlbum,
  ProjectCarouselCard,
  SkillsByCategory,
  TimelineElementExperience,
} from "./types";

// https://heroicons.com/outline

export const ExperienceSectionData: TimelineElementExperience[] = [
  {
    id: 1,
    jobPosition: "founder",
    companyName: "Dychool",
    companyLogo: require("../src/assets/accel-learning-logo.png"),
    location: "Jharkhand, India",
    date: "Nov 2021 – Aug 2022",
    description: [
      "All of us felt disengaged during COVID, particularly students like us whose classes were online with not much interaction.",
      "why there is no social network for learning? At that time i was learning a lot by just being in community and i found specially for learning we need a platform for that. So i started working on this project.",
      "we have LinkedIn for professionals and GitHub for coders, but why not something for School students? ",
      "To make it reality i had to learn coding so i started from web app development.(learned JavaScript, HTML, CSS, React and Python) ",
      "but as things are being built. a few companies like @skool came (they were doing the same work), and I thought it is not a fruitful thing to work!!"
    ],
    skillsUsed: ["JavaScript", "HTML", "CSS", "React", "Project Management", "Education Technology"],
    links: [],
  },
  {
    id: 2,
    jobPosition: "AI workflow builder",
    companyName: "",
    companyLogo: require("../src/assets/mission-mentor-logo.png"),
    location: "Mumbai",
    date: "Aug 2021 – Apr 2022",
    description: [
      "when chatGPT launched, from the first day i started using that and then i fascinated by how it works under the hood?.",
      "Started learning Neural Networks read bunch of papers and then shifted my focus to build actual usecases and products using AI.",
      "I started with Python plus LLM and built basic chatbot started exploring Langchain and gradually to low code automation tools like n8n and make.com.",
      "Everyday when new open source model come out i used to test that with ollama or huggingface and github.",
      "Started building complex workflows which actually solving actual business problems.",

    ],
    skillsUsed: ["Langchain", "Python", "LLMs", "n8n", "Automation"],
    links: [],
  },
  {
    id: 3,
    jobPosition: "Operation Intern",
    companyName: "Pixie Job",
    companyLogo: require("../src/assets/cisco-logo.png"),
    location: "Andheri, Mumbai",
    date: "May 2024",
    description: [
      "Joined a small recruitment company as an Intern, where I was responsible for business development and operations (company was far behind in technology and had a large customer base), everything was being manually done.",
      "Formulated and presented innovative solutions for automating 4 Task which i observed first was Automated Calling and Messaging System , In order to make it Possible i built a basic protoype of this system in 7 days and rest of 3 task were interconnected to it.",
      "We were able to make 5 calls in 1 trigger but at that time due to some hallucination and heavy costing i decided to quit.",
    ],
    skillsUsed: ["Communication Skills", "Automation", "Problem Solving", "Leadership"],
    links: [],
  },
  {
    id: 4,
    jobPosition: "AI Visuals and Filming",
    companyName: "Humanish AI (YT Channel)",
    companyLogo: require("../src/assets/jane-street-logo.png"),
    location: "Mumbai",
    date: "Jul 2024 – Aug 2024",
    description: [
      "from the very early days of my career i was always fascinated by Films and visual storytelling. while i was get in touch with every AI updates (subcribed to multiple channels and newsletters) so writing story first simultanesly experimenting with Tools like runwayML , Midjourney, Ideogram, flux model and more complex ComfyUI.",
      "Learned How to Train your own Voice locally using open source models plus how to interchanged one voice to another voice with accurate modulations. we were able to get accurate results.",
      "It took me one month to creating my first ever short film (10 mins) from script to final concept and visuals to dialogues and music, it was too much fun.",
    ],
    skillsUsed: ["Storytelling", "ComfyUI", "Scripting", "Open Source Models"],
    links: [],
  },
  {
    id: 5,
    jobPosition: "BTECH AI/ML",
    companyName: "Universal AI University",
    companyLogo: require("../src/assets/vertice-ai-logo.png"),
    location: "Karjat, Mumbai",
    date: "Aug 2024",
    description: [
      "Doing my Engineering in Artificial Intelligence and Machine Learning to further enhancing my knowledge in AI research and development.",
      "It's exciting time to experimenting new things as of now i am more into building autonomous workforces wheither it's salesman , telecallers or CRM managers or content creations",
      "I have been building AI agents it's exciting field to be in. ",
    ],
    skillsUsed: [
      "Python",
      "Langchain",
      "Open Source",
      "Backend",
      "Langraph",
      "N8N",
      "Docker",
      "Llamaindex",
      "RAG",
      "Agentic RAG",
      "Long Term Memory",
      "Databases",
    ],
    links: [],
  },
  {
    id: 6,
    jobPosition: "Founder",
    companyName: "Bladex AI",
    companyLogo: require("../src/assets/vertice-ai-logo.png"),
    location: "Mumbai",
    date: "Jan, 2025",
    description: [
      "From my day while working as a intern i saw the same problem in many companies and small businesses.",
      "Every company has CRMs but that requires a lot of manpower and it's time consuming.(we are building specialised AI agents to interact with customers aligned with company's needs and policy.)",
    ],
    skillsUsed: [
      "Flask",
      "Python",
      "AI Agents",
    ],
    links: [],
  },
];

export const ProjectsSectionData: ProjectCarouselCard[] = [
  {
    id: 1,
    image: require("../src/assets/munch.png"),
    title: "Munch",
    description:
      "A social culinary hub for college students to buy/sell homecooked meals and discover recipes created by other students.",
    fullDescription:
      "Munch is a social culinary hub for college students to buy/sell homecooked meals and discover recipes created by other students. The application was developed using a cross-platform mobile application with cached state-management, scalable persistent data storage, and a gateway authentication layer using relational database systems, a Prisma object relational mapper, and AWS services.",
    skillsUsed: [
      "React Native",
      "Redux",
      "AWS",
      "PostgreSQL",
      "GraphQL",
      "Firebase",
      "Node.js",
      "React.js",
      "TypeScript",
      "HTML",
      "CSS",
    ],
    projectLink: "https://joinmunch.app",
    additionalLinks: [],
  },
  {
    id: 2,
    image: require("../src/assets/tutorconnect.png"),
    title: "Tutor Connect",
    description:
      "A web application that connects students with tutors for personalized learning experiences.",
    fullDescription:
      "Tutor Connect is an online platform that allows high school students to instantly connect with qualified and verified tutors. The site was quickly adopted by the Secaucus Public School District and serves over 500 students and 60 verified tutors daily. The platform comes fully equipped with an administator dashboard that allows school staff to manage student permissions, view analytics, and gain insight into the platform's usage.",
    skillsUsed: [
      "React.js",
      "TypeScript",
      "HTML",
      "CSS",
      "Node.js",
      "Firebase",
    ],
    projectLink: "https://tutorconnect.sboe.org",
    additionalLinks: [],
  },
  {
    id: 3,
    image: require("../src/assets/signslate.png"),
    title: "Signslate",
    description:
      "A web application that allows users to speak and translate English to American Sign Language (ASL) and ASL to English in real-time.",
    fullDescription:
      "Signslate is a web application that allows users to speak and translate English to American Sign Language (ASL) and ASL to English in real-time via webcam or microphone input and displays the ASL translation using web-scraped videos. The site web-scrapes videos off the internet using a Flask python server and displays them on a ReactJS frontend for translating speech to ASL. To translate ASL to English, the site uses a custom trained machine learning model to recognize ASL gestures and translate them to English. The site received 1st place in the Diversity and Inclusion Category of the High Tech Hacks 2021 Hackathon, 1st place overall in the Simplihacks 2021 Hackathon, and won the Wolfram Alpha Award.",
    skillsUsed: [
      "React.js",
      "Python",
      "Flask",
      "TypeScript",
      "HTML",
      "CSS",
      "Node.js",
      "Firebase",
    ],
    projectLink: "https://github.com/krushaybhavsar/signslate",
    additionalLinks: [],
  },
  {
    id: 4,
    image: require("../src/assets/tileshift.png"),
    title: "Tileshift",
    description: "A daily web-based word puzzle game.",
    fullDescription:
      "Tileshift is a daily web-based word puzzle game. The goal of the game is to align tiles to spell a word and turn them green. To win the game, players must use all the tiles within thirty moves. Players can also compete against friends and share their results. The site has gained over 125,000 hits on Reddit with an estimated 410 players across 3 different continents and an average engagement time of 7 minutes and 40 seconds per user.",
    skillsUsed: [
      "React.js",
      "TypeScript",
      "HTML",
      "CSS",
      "Node.js",
      "Firebase",
    ],
    projectLink: "https://tileshiftgame.com",
    additionalLinks: [],
  },
  {
    id: 5,
    image: require("../src/assets/privalink.png"),
    title: "Privalink",
    description:
      "A platform to generate secure, private, and encrypted self-destructive links for sharing sensitive information.",
    fullDescription:
      "Privalink allows you to send any sensitive data or information to people you trust using self-destructing links. After someone has viewed the link, all sensitive data will be deleted from the Firebase firestore and the link will no longer be available for use. The site also gives users the option to instantly get notified via email after the link is opened and to set an expiration date for the link.",
    skillsUsed: [
      "React.js",
      "TypeScript",
      "HTML",
      "CSS",
      "Node.js",
      "Firebase",
    ],
    projectLink: "https://privalink.app",
    additionalLinks: [],
  },
];

export const SkillsSectionData: SkillsByCategory[] = [
  {
    categoryTitle: "Programming & Markup Languages",
    skills: [
      { name: "TypeScript" },
      { name: "JavaScript" },
      { name: "Python" },
      { name: "Java" },
      { name: "C" },
      { name: "C#" },
      { name: "SQL" },
      { name: "HTML" },
      { name: "CSS" },
      { name: "XML" },
      { name: "MATLAB" },
    ],
  },
  {
    categoryTitle: "Frameworks & Libraries",
    skills: [
      { name: "React.js" },
      { name: "React Native" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "Next.js" },
      { name: "Electron" },
      { name: "GraphQL" },
      { name: "Prisma" },
      { name: "Redux" },
      { name: "Spring Boot" },
      { name: "Flask" },
      { name: "Django" },
      { name: "OpenCV" },
      { name: "NumPy" },
      { name: "TensorFlow" },
    ],
  },
  {
    categoryTitle: "Tools",
    skills: [
      { name: "PostgreSQL" },
      { name: "Amazon Web Services (AWS)" },
      { name: "Firebase" },
      { name: "Git" },
      { name: "Jira" },
      { name: "Figma" },
      { name: "Android Studio" },
      { name: "Unity" },
      { name: "Arduino" },
      { name: "Processing" },
    ],
  },
];

export const EndorsementsSectionData: Endorsement[] = [
  {
    headshot: require("./assets/patrick-moloney.jpeg"),
    name: "Patrick Moloney",
    title: "Head of Product at Vertice AI",
    content:
      "Krushay was a phenomenal addition to the team throughout the duration of his internship with Vertice AI. He constantly impressed us, beating deadlines, taking leadership, coming up with innovative solutions.",
    context: "Worked with Krushay at Vertice AI",
  },
  {
    headshot: require("./assets/robert-wachen.jpeg"),
    name: "Robert Wachen",
    title: "Co-Founder & COO at Etched, Thiel Fellow",
    content:
      "Krushay is an awesome team member and software engineer. He consistently puts out clean, efficient, well-functioning code and does it faster than most programmers I know.\n\nKrushay worked on a team of MIT and Harvard engineers. Krushay not only pulled his own weight but also taught them how to write more scaleable code and use new frameworks and libraries. He's sharp, thinks from first principles, and is a joy to work with.",
    context: "Managed Krushay directly at Mentor Labs (acquired)",
  },
  {
    headshot: require("./assets/luke-weidner.jpeg"),
    name: "Luke Weidner",
    title: "Head of Engineering at Vertice AI",
    content:
      "100% recommend Krushay - we expected a lot from him at Vertice and he delivered. He's great to work with and was able to pick up our system very quickly.",
    context: "Managed Krushay directly at Vertice AI",
  },
];

export const PhotographyScreenData: PhotographyAlbum[] = [
  {
    id: 1,
    title: "Costa Rica",
    dir: "costa-rica",
    length: 14,
    imageHashes: [
      "UA8q~4IA8x*I-:M}Mzoy8wyC%#MJ4pxt-:jY",
      "UEC%BCCTvos#%%XWnTav5S=zNIbbNfxuNfbc",
      "U?AVO@W?WAj]X=floLfkMxjYkCa|nMjZWWaz",
      "U]G]XOadV@oe?df6axofxtofj]ofWAoej]j]",
      "UNCaYcIdH;-QeBoHSwXS.TtSVqjD.9R,Mvt6",
      "U*FZNfxujYod?wt7ofoLofj[ogofRjWBaeof",
      "UEMshvozD,-.~lxGWB$~M}x?9d9J=@NHR*s+",
      "U7F7p@DAEv%^I^03mpM|01Dk,LrvHcDR*D.Q",
      "UHGI;tTH.O??J5fUjK%cICR$M|I.InD*IUIU",
      "UbF6wrO_pLxv%iNGRjt6RORNaKW?R*jct7Rk",
      "UN9*ogx|t:x_R4neoYV?9ERiRORibcWGWEax",
      "UJG7*h$%5SxC~Bs:R+oIOsS#WEslNeofkCjY",
      "URD[:}s:E2WV~BoMNHayEka}s.a#9~bHxZaz",
      "U9Bp]|t-9Fny~pb_t2RO%NjYE0M|ozxCIoRp",
    ],
  },
  {
    id: 2,
    title: "Abu Dhabi",
    dir: "abu-dhabi",
    length: 6,
    imageHashes: [
      "UhGuRPofIpof~qj[Rkj[S*j[s,a}9vj[t5az",
      "UaE.kOS5E2xZ~WWYIps:o#a#j[WCE5oLt6Rk",
      "UIDT}2:zv{ktgS$_oHRi9jtTt7n#-NR:kBt7",
      "U9HCQROwtl?G00D*IAbw4V-h.8IV~o=?MxNf",
      "U5Hw#*-T01-o.mj[MyWB-=s.NKazIYaybdWX",
      "UHAme=^+t5s:?w-ps.of9vRkaxfQ9FIVR+ay",
    ],
  },
  {
    id: 3,
    title: "New York City",
    dir: "nyc",
    length: 8,
    imageHashes: [
      "UoE|GGX9t7ogpfbcj[bIIAoJWBaes7WBkCay",
      "U;E:rco#RjjZ?wkDayj[o#WCs:ogRjRij[j]",
      "U+FZKdt7oJoe.TkCfkj]OaW=a#a}NLjsayf6",
      "USE|JJxttQxsG1xsofWVDjNHWXf6jEt6kCof",
      "U]9Iu;yGtSkCkDkCf6aeaeayazayj]j]j[fQ",
      "U15N_p5t00}Q0|$L}s1O}tEM5Q^3JVxa$y9v",
      "UjGuwS%1jEof~qxVjsofOZofoJjZE3WrofoL",
      "U6BW}7.600D#NQ%2aIDi9.4tMc$_Dgox?wj?",
    ],
  },
  {
    id: 4,
    title: "Atlanta",
    dir: "atlanta",
    length: 8,
    imageHashes: [
      "UrBO2bkDX9WAlCkEofadNOkXn}oJngbcV?f5",
      "UaEB?dXSNGxF~EozR*oLXoxaoJS2Ehsos.WW",
      "U56a-y%jMvRNN*R:W9of00itxwp0r,aKo$aw",
      "U15q*BD*00~A00%LtR4;S^wH-o-:9GK6%1Mx",
      "U77T,:j[0LjbJ7ayxZj[0Kay~Bfk^jbH9vjZ",
      "Ue1rBaacaKkElCacaekDkXacfRkAjEadf+kC",
      "UF0ob6lCZzaikbj_aee.kjk8aKf6e]flf+fl",
      "UF0MToeke5e*dCg6gPfTeiemfnf,glfhf-f,",
    ],
  },
  {
    id: 5,
    title: "Açores",
    dir: "acores",
    length: 21,
    imageHashes: [
      "U@A2ZGjZaeogTOWCf6WYVvj@ofj?nLjsbIa{",
      "UoCj*9ktRkt6.AkXRjt7x]V@V@t7t7RjjYt6",
      "UfB|dEE3aIay?wIqaej?tUWDjrkCI[s:ogoe",
      "USC%5Jt7E2f5~qjZIpj]kWj[jua#ESkCslWC",
      "URBz5@9aNG%1?wIVR*t6ETxBs.R,E2xZoeR*",
      "U~B}h5n}oKoft:ofj@j]o~kDjufQRnbIbHfP",
      "UVEyrcRPRixa_4t8V@s.bxxus+oJkYt7xYt6",
      "U~Ctw@t6fjbIyGoffkbINMkCj]a#M_WWjuj[",
      "UmB4LBf4ROof.ARjROkC%iV@RifP%OWBaeax",
      "UWDSgxD+WVoI~WIVWqn$kXjEkCjYENxZj[ae",
      "U~F6^VSislof.AS6j[ofohR.WYj?RPWDjsj?",
      "UmEV{U$yM{o#?wxXR-WXtmt6ofWBR:S4oJs:",
      "U?DmtB$|oIkC?wxtoKoLx^t7ocj?WGj@odj[",
      "UJDuxd0is*jG~VIrWAj[0i=_RQkCE3%0Rkoy",
      "UIBDA{rqV@%0?wnhWAaz0$bca|IqE1X9oeof",
      "Uw8PNDbIWAkCpMj[j?fkMyaekCf6Vqf6a#fQ",
      "UyFsYwtRWBt6?dogWBof%NWUazoftQV@j[j]",
      "U?GSy8NMfkWY?wNIj[a#aeV@odjsM{oJoeay",
      "UhC7m2%ht2obx|xws+j=p1o#aKj[X9W-acbI",
      "UrG]2S%%NHROa#R+WXs:t7WCa#oft7WVofj[",
      "UMFiABxuE3kC.mkCxvof_4of%3s:.8of%3of",
    ],
  },
];
